name: Auto Cherry-Pick from Upstream

on:
  workflow_run:
    workflows: [ "Release GitHub Actions" ]
    types:
      - completed

  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to create the PR against"
        required: true
        default: "main"
      mode:
        description: "Run mode: cherry-pick or verify"
        required: false
        default: "cherry-pick"

  pull_request:
    types: [ opened, synchronize, labeled ]

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  cherry-pick:
    if: (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' || contains(fromJson(toJson(github.event.pull_request.labels)).*.name, 'review-required')
    uses: step-security/reusable-workflows/.github/workflows/auto_cherry_pick.yaml@v1
    with:
      original-owner: "zizmorcore"
      repo-name: "zizmor-action"
      base_branch: ${{ inputs.base_branch || 'main' }}
      mode: ${{ github.event_name == 'pull_request' && 'verify' || inputs.mode || 'cherry-pick' }}
